### ISSUE TITLE
Failed creating new xdo instance.

### ISSUE THREAD

**Issue by ghost** [Mabox-Linux/mcorners#1]
When launching it just spams the message "Failed creating new xdo instance."

xdotool version 3.20211022.1
xprop 1.2.7

**Comment by napcok** [comment]
What  DE/WM you use?
Is DISPLAY environment variable set?

    env|grep DISPLAY

**Comment by ghost** [comment]
CTWM, yes DISPLAY is set on all XScreens.

**Comment by ghost** [comment]
So I decided to poke around and say the source is just a bash script. So I just saved the raw to my desktop and started to look through things. It's a tad fiddly but it works if I run it from the file I saved but the initial git clone just spams the xdo message.

I actually got the script to trigger the xdo issue again. Looks like it's an issue where inputs aren't strictly checked and syntax issues can happen based on the term used. If I run it with DISPLAY=:0.1 there is some potential for it to actually be DISPLAY=:0.1./mcorners or :0.1.0. Yeah just tested in xterm and it's OK but in Sakura/Terminator it starts to do some odd things where text is overwritten or displayed wrong. If I manually launch with say DISPLAY=:0.1.0 it spams the message so my initial launch and subsequent tries somehow had the DISPLAY malformed.

I had to comment out the $DB lock bits though other wise you can only run on a single XScreen. It also likes to bounce the mouse from the triggering edge.

Thanks btw.
